### ISSUE TITLE
Possible PermissionError with the donate executables 

### ISSUE THREAD

**Issue by codeoffun2** [revoxhere/duino-coin#1049]
**Describe the bug**
very time i start the miner, i get this error and the window closes
```
6:00:12  net0  Searching for the fastest node to connect to
Traceback (most recent call last):
  File "PC_Miner.py", line 866, in <module>
  File "PC_Miner.py", line 221, in load
PermissionError: [Errno 13] Permission denied: 'Duino-Coin PC Miner 2.73/Donate.exe'
[12736] Failed to execute script PC_Miner

```

**To Reproduce**
1. click on miner
2. wait for it to load

**Expected behavior**
The pc miner was supposed to run

**Screenshots/photos**

**System (please complete the following information):**
 - OS: Windows
 - Software PC_miner
 - Version 2.73

**Additional context**

**Comment by revoxhere** [comment]
Set the donation level in Settings.cfg file to 0

**Comment by codeoffun2** [comment]
> Set the donation level in Settings.cfg file to 0

oh yeah, i forgot to tell you it works after i restart
and when i close it and run it again, it stops working
