### ISSUE TITLE
Cant run on Ubuntu Focal Fossa (20.04.3)

### ISSUE THREAD

**Issue by rasongame** [revoxhere/duino-coin#1052]
**Describe the bug**
On Debian Buster or Ubuntu Focal Fossa (Ubuntu in docker),  PC_Miner cant run with this error 
```
root@7d579982dce6:/2.7.3# ./PC_Miner
[4856] Error loading Python lib '/tmp/_MEIJMF9Ml/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/_MEIJMF9Ml/libpython3.9.so.1.0)

```
**To Reproduce**
1. Download and unpack release
2. Run
3. See error

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: Ubuntu or Debian
 - Software PC_Miner
 - Version 2.7.3

**Comment by revoxhere** [comment]
Are you running a 32 bit OS?

**Comment by rasongame** [comment]
No, 64 bit OS.
```
rason@homeserver ~> uname -a
Linux homeserver 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

**Comment by revoxhere** [comment]
Does running from source work?

**Comment by rasongame** [comment]
Yeah, its running from source. I think, trouble in a release, because it have a bundled python.
`rason@homeserver ~/m/duino-coin> python3 PC_Miner.py                                                                                                                      Xxhash is not installed - this mining algorithm will be disabled                                                                                                                                                                                                                                                                                    Duino-Coin basic configuration tool                                                                                                                                       Edit Duino-Coin PC Miner 2.74/Miner_config.cfg file later if you want to change it.                                                                                       Don't have an Duino-Coin account yet? Use Wallet to register on server.                   `

**Comment by BastelPichi** [comment]
> **Describe the bug** On Debian Buster or Ubuntu Focal Fossa (Ubuntu in docker), PC_Miner cant run with this error
> 
> ```
> root@7d579982dce6:/2.7.3# ./PC_Miner
> [4856] Error loading Python lib '/tmp/_MEIJMF9Ml/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/_MEIJMF9Ml/libpython3.9.so.1.0)
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Download and unpack release
> 
>     2. Run
> 
>     3. See error
> 
> 
> **Screenshots/photos** If applicable, add screenshots or photos to help explain your problem.
> 
> **System (please complete the following information):**
> 
>     * OS: Ubuntu or Debian
> 
>     * Software PC_Miner
> 
>     * Version 2.7.3

Try to run: `sudo apt install libc6`

**Comment by BastelPichi** [comment]
Closed due to inactivity, feel free to reopen if the problem persits.
