### ISSUE TITLE
python 3 PC_miner not working on raspberry pi.

### ISSUE THREAD

**Issue by nickbey06** [revoxhere/duino-coin#1060]
python3 PC_Miner.py
  File "PC_Miner.py", line 200
    pretty_print(f"Warning: {response['message']}"
                                                                            ^
SyntaxError: invalid syntax

----------------------------------------------------------------------------------------------

python3 PC_Miner.py
  File "PC_Miner.py", line 273
    if val >= 1_000_000_000_000:  
                                                ^
SyntaxError: invalid syntax

**Comment by revoxhere** [comment]
Your python is outdated. You need at least 3.7 or 3.8

**Comment by BastelPichi** [comment]
Closed due to inactivity, feel free to reopen if the porblem persists.
