### ISSUE TITLE
Once again about json request

### ISSUE THREAD

**Issue by gravedigger21** [revoxhere/duino-coin#1066]
I was overjoyed early [1065](https://github.com/revoxhere/duino-coin/issues/1065).
If I send a request from the browser https://server.duinocoin.com/users/user_name  then everything is ok, I get a response in json format.
If send a request from arduino
client.println ("GET / users /user_name HTTP / 1.1 \ r \ nHost: server.duinocoin.com \ r \ nConnection: close \ r \ n \ r \ n");
I get nothing in return. What am I doing wrong?

**Comment by revoxhere** [comment]
How are you fetching the data?

**Comment by gravedigger21** [comment]
![photo_2021-10-19_21-15-58](https://user-images.githubusercontent.com/89804661/137969483-744d5d15-9a2d-4dda-b023-70a98c54db06.jpg)

finished off

**Comment by revoxhere** [comment]
Nice work!
