### ISSUE TITLE
Your Wiki might have been hacked

### ISSUE THREAD

**Issue by parg** [revoxhere/duino-coin#1072]
User kirniko added a download link to 

https://github.com/kirniko/duino-coin/releases/tag/2.7.3

Have a nice day

**Comment by gsrbr** [comment]
Hello @parg , thanks for report it :smiley: We are already reviewing repository permissions

**Comment by gsrbr** [comment]
Changes reversed, permissions revised and issue resolved... Again, thanks for report it 😃

I'm closing this issue, but feel free to reopen it.
