### ISSUE TITLE
Problem with latest Arduino_Code on Raspberry Pi Pico

### ISSUE THREAD

**Issue by k1l0kn4113r** [revoxhere/duino-coin#1501]
After uploading the latest Arduino_Code to one of my RPI Pico's the AVR Miner keeps rejecting and it looks like the COM port will reconnect  every couple of  minutes. I have tried the AVR miner on both Windows and Linux same result.
![2022-05-09_20h37_49](https://user-images.githubusercontent.com/50697165/167478380-39f1e0c0-dd71-4290-95e3-89d1c0bc572e.png)
Is there a fix for this issue?

**Comment by darrenleesmith** [comment]
I am getting exactly the same thing, I thought it was just me.

**Comment by darrenleesmith** [comment]
> After uploading the latest Arduino_Code to one of my RPI Pico's the AVR Miner keeps rejecting and it looks like the COM port will reconnect every couple of minutes. I have tried the AVR miner on both Windows and Linux same result. ![2022-05-09_20h37_49](https://user-images.githubusercontent.com/50697165/167478380-39f1e0c0-dd71-4290-95e3-89d1c0bc572e.png) Is there a fix for this issue?

Just tried it with V3.00 and it's perfect.

**Comment by k1l0kn4113r** [comment]
Change #pragma GCC optimize ("-O0") solves the issue
