### ISSUE TITLE
me too For username "refatelgenidi", i am unable to login to the DUCO web wallet.

### ISSUE THREAD

**Issue by granadaturkey** [revoxhere/duino-coin#1540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by granadaturkey** [comment]
me too For username "refatelgenidi", i am unable to login to the DUCO web wallet.

**Comment by LDarki** [comment]
To avoid having to respond to 2 different issues, we can talk in [this issue](https://github.com/revoxhere/duino-coin/issues/1538).
