### ISSUE TITLE
I cannot enter to my Duino Wallet

### ISSUE THREAD

**Issue by Manumetal** [revoxhere/duino-coin#1541]
I have lost all my DUCOs, I had 1227 on staking from 06/06/2022 and never returned to my wallet, all mined Duco since then disappeared as well.

![image](https://user-images.githubusercontent.com/35889547/180168770-2f18e37e-513c-4ac9-b5a4-4e27d6e1c1fb.png)
![image](https://user-images.githubusercontent.com/35889547/180168829-d2931dc9-c215-43f6-afc0-5a10f18897e4.png)

**Describe the bug**
I cannot enter to my Duino Wallet, it's like the account is no longer available
On password recovery shows "This user doesn't exist"

**To Reproduce**
1. Go to '(https://wallet.duinocoin.com/)'
2. Put user and pass
3. Hit login
4. No error, just shaking the username

**Expected behavior**
Enter to the wallet

**Screenshots/photos**
![image](https://user-images.githubusercontent.com/35889547/180167046-8926f0b3-d48e-4859-947f-0943ae6b822d.png)
![image](https://user-images.githubusercontent.com/35889547/180167190-699bc390-95fa-4ae1-b344-dd5555df00c3.png)

**System (please complete the following information):**
 - OS: [Win 10 x64]
 - Software [AVR Miner]
 - Version [2.4]
- Chrome & Edge
**Additional context**

**Comment by LDarki** [comment]
Hi, can you send me your wallet username ? I want to see something.

**Comment by Manumetal** [comment]
Hi,

      Username: manumetal
________________________________
De: LDarki ***@***.***>
Enviado: jueves, 21 de julio de 2022 9:15
Para: revoxhere/duino-coin ***@***.***>
Cc: Manumetal ***@***.***>; Author ***@***.***>
Asunto: Re: [revoxhere/duino-coin] I cannot enter to my Duino Wallet (Issue #1541)


Hi, can you send me your wallet username ? I want to see something.

**Comment by LDarki** [comment]
![image](https://user-images.githubusercontent.com/51938450/180180049-44457be9-7cf8-459e-b5b7-369ed6a42aed.png)
Your user exists so maybe it's another issue.
Try using incognito mode or another browser.

**Comment by Manumetal** [comment]
Yeah, at the end I can enter creating "new" user with the same credentials, but I have lost 1227 Duino on stake and has no minned nothing since 06/06/2022 (24x7 miner on)
________________________________
De: LDarki ***@***.***>
Enviado: jueves, 21 de julio de 2022 9:27
Para: revoxhere/duino-coin ***@***.***>
Cc: Manumetal ***@***.***>; Author ***@***.***>
Asunto: Re: [revoxhere/duino-coin] I cannot enter to my Duino Wallet (Issue #1541)


[image]<https://user-images.githubusercontent.com/51938450/180180049-44457be9-7cf8-459e-b5b7-369ed6a42aed.png>
Your user exists so maybe it's another issue.
Try using incognito mode or another browser.

**Comment by LDarki** [comment]
So, you want these ducos back?

**Comment by Manumetal** [comment]
Yeah, of course, 1227 Ducos staked and "I don't know the quantity" mined during this 5 weeks
________________________________
De: LDarki ***@***.***>
Enviado: jueves, 21 de julio de 2022 10:07
Para: revoxhere/duino-coin ***@***.***>
Cc: Manumetal ***@***.***>; Author ***@***.***>
Asunto: Re: [revoxhere/duino-coin] I cannot enter to my Duino Wallet (Issue #1541)


So, you want these ducos back?

**Comment by LDarki** [comment]
Done, here's the [transaction hash](https://explorer.duinocoin.com/?search=f179977bdc43bc1b8a9ed2978f73560a424b47ad).
I'll close this issue

**Comment by Manumetal** [comment]
Perfect! Many thanks!
________________________________
De: LDarki ***@***.***>
Enviado: jueves, 21 de julio de 2022 11:02
Para: revoxhere/duino-coin ***@***.***>
Cc: Manumetal ***@***.***>; Author ***@***.***>
Asunto: Re: [revoxhere/duino-coin] I cannot enter to my Duino Wallet (Issue #1541)


Done, here's the transaction hash<https://explorer.duinocoin.com/?search=f179977bdc43bc1b8a9ed2978f73560a424b47ad>.
I'll close this issue
