### ISSUE TITLE
I cannot enter to wallet

### ISSUE THREAD

**Issue by Manumetal** [revoxhere/duino-coin#1568]
**Describe the bug**
The password shows token outdated or something like that, it happened for second time, I cannot enter to my wallet and to duincoin main web.

**Comment by revoxhere** [comment]
You have to login again.

**Comment by Manumetal** [comment]
Still not working, could you reset my password? The reset tool is not working.
________________________________
De: Robert Piotrowski ***@***.***>
Enviado: sábado, 1 de octubre de 2022 9:45
Para: revoxhere/duino-coin ***@***.***>
Cc: Manumetal ***@***.***>; Author ***@***.***>
Asunto: Re: [revoxhere/duino-coin] I cannot enter to wallet (Issue #1568)


You have to login again.
