### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 5uh3** [revoxhere/duino-coin#1786]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by revoxhere** [comment]
Congrats on posting an issue template.

**Comment by 5uh3** [comment]
Congrats on posting an issue template.
