### ISSUE TITLE
I'm OSAMAH AHMED.

### ISSUE THREAD

**Issue by thecode3** [revoxhere/duino-coin#315]
Hi
Please, can I put an interrogation on this matter? If the matter concerns you, then you must answer me ..... because I want to answer
Regarding the use, I am a person who used it, and can I make some modifications to it because I want it as a fixed programming based on it being ready .... I wanted your permission to make changes to the project that belongs to you. It includes something like the templates you have because you are tired in your project because the project that you have can anyone download it ..... >>>>>>>>>>>>>>>>>>> But respect is a duty >>>>> >>>>>>>>>>>
I am from Libya. Libyan nationality.
I speak Arabic. If you do not understand me, please calm down a little and try to get closer to the meaning a little to understand it.
I have a British language from british council

**Comment by revoxhere** [comment]
Hello. I'm not sure if I understand you correctly, But if you want to make some changes or improvements then go ahead - we're an open source community and accept pull requests.

**Comment by rnbunker** [comment]
> Hi
> Please, can I put an interrogation on this matter? If the matter concerns you, then you must answer me ..... because I want to answer
> Regarding the use, I am a person who used it, and can I make some modifications to it because I want it as a fixed programming based on it being ready .... I wanted your permission to make changes to the project that belongs to you. It includes something like the templates you have because you are tired in your project because the project that you have can anyone download it ..... >>>>>>>>>>>>>>>>>>> But respect is a duty >>>>> >>>>>>>>>>>
> I am from Libya. Libyan nationality.
> I speak Arabic. If you do not understand me, please calm down a little and try to get closer to the meaning a little to understand it.
> I have a British language from british council

You use Pull Requests on Github to contribute to Projects if you don't have write Access. More Details here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
