### ISSUE TITLE
consider the alternative

### ISSUE THREAD

**Issue by 9ahmed** [revoxhere/duino-coin#335]
you  can try this.

why kolka? is there a reason for using kolka? when you can use anything except kolka. I suggest you can use BrandielotAlgorithmsCompany new product:

HIDDEN PRODUCT FOR SECURITY REASONS

for more information [CONTACT THIS](rnbunker@riseup.net)

**Comment by 9ahmed** [comment]
rnbunker check ur email rn i have sent

**Comment by EinWildesPanda** [comment]
Shut up and stop spamming the issues with nonsense.

**Comment by rnbunker** [comment]
> you can try this.
> 
> why kolka? is there a reason for using kolka? when you can use anything except kolka. I suggest you can use BrandielotAlgorithmsCompany new product:
> 
> HIDDEN PRODUCT FOR SECURITY REASONS
> 
> for more information [CONTACT THIS](rnbunker@riseup.net)

I approve of this
