### ISSUE TITLE
proposedChanges

### ISSUE THREAD

**Issue by rnbunker** [revoxhere/duino-coin#344]
replace dui*ocoin website with something like this:
http://motherfuckingwebsite.com/
or atleast remove the LSD CSS Barrel roll moving Dui*ocoin logo and get rid of Goo*le Analytics

**Comment by PhereloHD** [comment]
getting rid of google analytics is a good point.

**Comment by revoxhere** [comment]
Why should I replace the website with something entirely unrelated?

**Comment by rnbunker** [comment]
That's why I said something ***LIKE*** this

**Comment by rnbunker** [comment]
bruh

**Comment by Abb1x** [comment]
Tbh the website gives me epilepsy
