### ISSUE TITLE
PearGameEngine

### ISSUE THREAD

**Issue by 9ahmed** [revoxhere/duino-coin#359]
## review of PearGameEngine...  

PROs

1. widely used amongst few people
2. working hard to combat battle 
3. boo-bed spy left red green
4. yellow

CONs

1.  Pakistan influence
2. German influence
3. matese influence
4. "INPUT LAG"
5. spy in webcam causing peripheral damage
6. not considering AI and other new techs..
7. created by indians influence
8. "Henry"
9. causing CPU to crumble and ram to slide off DIM1 and DIM4 
10. causing hierarchy == bad == capitalism

### Tom heisen Adolf

has caused ME AND MY FAMILY mental health issues as a side effect of "CODE"

### Muller 

ARE YOU KIDDIENG?!?! I WILL NOT SAY A WORD! 

respectfully,
+instapfp

**Comment by Bilaboz** [comment]
Please stop spamming random issues or you will get banned from this repo

**Comment by 9ahmed** [comment]
i find this to be completely relavent to our chat over on IRC rnbunker.ydns.eu/6667 (Ssl config is broken for now)

**Comment by 9ahmed** [comment]
+ that is racial

**Comment by phrl42** [comment]
b r u h
