### ISSUE TITLE
Arduino Nano Not Working With Latest Update Version

### ISSUE THREAD

**Issue by thecode3** [revoxhere/duino-coin#441]
Arduino Nano Not Working With Latest Update Version >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

This Example With Debug
Data Mining Empty Not From Board Because The Older Version Work 100%
![Untitled](https://user-images.githubusercontent.com/56282088/116168922-dbd76900-a703-11eb-990e-5081eaa8f834.jpg)

And This One With Older Version 

![Untitled2](https://user-images.githubusercontent.com/56282088/116168789-88651b00-a703-11eb-88a8-19cce68f682e.jpg)

**Comment by revoxhere** [comment]
Have you uploaded the 2.45 code to your arduino board?

**Comment by thecode3** [comment]
> هل قمت بتحميل كود 2.45 على لوحة اردوينو الخاصة بك؟

yes. But Stay the Same Problem.

**Comment by BastelPichi** [comment]
> Have you uploaded the 2.45 code to your arduino board?

I sometimes get that error too, with older vrsions of the code i never get that.

**Comment by M-O-N-Q** [comment]
Mine too, I tried mining on a Nano today using the latest arduino miner and AVR miner, but the miner stopped at 43/44 and 44/45. I have tried restarting it and it worked, then after a few mins, the mining stopped again.

**Comment by revoxhere** [comment]
If you can install python, use the avr miner version from the source

**Comment by M-O-N-Q** [comment]
I'll try it later, thanks

**Comment by joaquinbvw** [comment]
I just saw this issue. Have this been resolved yet?

**Comment by thecode3** [comment]
I'm sorry, I'm some time I can't open GitHub because GitHub take more balance of package internet my network
