### ISSUE TITLE
PC Miner config

### ISSUE THREAD

**Issue by httsmvkcom** [revoxhere/duino-coin#51]
![изображение](https://user-images.githubusercontent.com/51028674/100922903-77670380-34ef-11eb-8154-a8f4e3c19136.png)
I try on PC and VPS but nothing help

**Comment by revoxhere** [comment]
Try again, we were moving to a new database and in a short time we'll also be moving to a new VPS server so there may have been some accesibility issues

**Comment by httsmvkcom** [comment]
This problem has been with the v1.6 and 1.7 versions for a week now, and I don't think the problem is with the server

**Comment by revoxhere** [comment]
Ok, I will check if your account didn't get corrupted

**Comment by revoxhere** [comment]
Make sure you're inputting values for the mining intensity and autorestarter, this may be causing an error, I didn't realize someone can just skip these - I'll add some default values for the next version.
