### ISSUE TITLE
Bro the new feature called Public node keeps crashing every 5-10min

### ISSUE THREAD

**Issue by Shreyas-Dev-ITB** [revoxhere/duino-coin#694]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by sys-256** [comment]
The is probably a server issue, I started my node at around 12:30, and it stopped at 16:00, so it ran just fine for about 3,5 hours. But now that more people are running a node, the server can't send enough responses or something

**Comment by revoxhere** [comment]
Node is curretly more for demonstrational purposes and a more ready to use version will be released soon
