### ISSUE TITLE
Public node

### ISSUE THREAD

**Issue by Shreyas-Dev-ITB** [revoxhere/duino-coin#696]
**Describe the bug**
A clear and concise description of what the bug is

**Expected behavior**
Runs fine but after 5-10 min running it crashes and closes the problem

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: windows
 - Software : Public node
 - Version :2.5.7

**Additional context**
Please fix that crashing issue

**Comment by revoxhere** [comment]
Node is curretly more for demonstrational purposes and a more ready to use version will be released soon
