### ISSUE TITLE
Python39.dll

### ISSUE THREAD

**Issue by Moe-123** [revoxhere/duino-coin#698]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows 7]
 - Software [e.g. PC Miner]
 - Version [e.g. 2.4]

**Additional context*
![20210724_052638](https://user-images.githubusercontent.com/85011088/126855011-dd2dd92b-000c-498b-b751-f39584670c07.jpg)
Why is it not working ?

**Comment by sys-256** [comment]
Try running it from source by cloning the repo and then running PC_Miner.py.

**Comment by Moe-123** [comment]
> حاول تشغيله من المصدر عن طريق استنساخ الريبو ثم تشغيل PC_Miner.py.

I tried, but it appears that there is an error in the lines

**Comment by sys-256** [comment]
Well, there isn't a bug or error in the code, since it runs fine for me and many others. I see that you are using the MingW64 terminal, try using the normal command prompt or the PowerShell.
