### ISSUE TITLE
Why is there no mining system for the phone partially deactivated ?

### ISSUE THREAD

**Issue by Moe-123** [revoxhere/duino-coin#699]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I have three phones that have a malfunction in touching the screen due to the breakage, but it works normally. How can it be used?

**Comment by shruuub** [comment]
You could try the Android Miner Cluster if you have one funktioning ( https://github.com/DoctorEenot/DuinoCoin_cluster ) But otherwise, I dont know how it could work, since to my knowlege you cant activate programs external (from a PC etc.)

**Comment by noobflix** [comment]
Eu posso ajudar tô fazendo o sistema com conjunto com o termux com root e sem root
