### ISSUE TITLE
Error in line 6 

### ISSUE THREAD

**Issue by Moe-123** [revoxhere/duino-coin#702]
![20210724_174831](https://user-images.githubusercontent.com/85011088/126872257-2d976510-4119-4563-8d8b-df4170781408.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by revoxhere** [comment]
You're probably using python2 instad of 3

**Comment by sys-256** [comment]
It probably doesn't recognize the copyright (©) logo on line 6, try removing the logo (or just whole line 6), and then run it again.
