### ISSUE TITLE
ESP8266 miner Don't mine any coin

### ISSUE THREAD

**Issue by mrgh14** [revoxhere/duino-coin#735]
ESP8266 miner Don't mine
  

> ### **Esp8266** miner work but no coin mined!?

Plz Solw Problem
Thank u Duino Coin
Tanke u Revox

**Comment by marcoduinocoin** [comment]
> ESP8266 miner Don't mine
> 
> > ### **Esp8266** miner work but no coin mined!?
> 
> Plz Solw Problem
> Thank u Duino Coin
> Tanke u Revox

Have you got the amount from me?

**Comment by BastelPichi** [comment]
Can you give more information? Like serial monitor screenshots?
