### ISSUE TITLE
upload file disabled

### ISSUE THREAD

**Issue by Srikanth99855** [revoxhere/duino-coin#772]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Srikanth99855** [comment]
github uploads are disabled       How to solve this problum

**Comment by gsrbr** [comment]
Hello,

You want to upload your code directaly to Duino Coin repository? 

If yes, you can't, for contribuit with the Duco you need to fork the project, make the alterations and apply to a merg. [See more on the github documentation](https://docs.github.com/en/github/collaborating-with-pull-requests)

If no, sorry, Can you explain better your problem? please.

**Comment by BastelPichi** [comment]
Can you explain your problems better?

> github uploads are disabled How to solve this problum
