### ISSUE TITLE
Mining rewards are extremely low

### ISSUE THREAD

**Issue by logdaubui** [revoxhere/duino-coin#803]
### hello i mine with 50 arduino but the mining share is very low ###
<img src="https://i0.wp.com/s1.uphinh.org/2021/08/13/Capture381dcb27cff17fea.png" alt="Capture381dcb27cff17fea.png" border="0" />

**Comment by logdaubui** [comment]
### haizz!!! I look forward to long-term stable mining ###

**Comment by Elheims** [comment]
Try using 10 arduino 😁

**Comment by naphob** [comment]
according to the new version of Kolka, earning rewards will significantly drop after 25 workers

**Comment by revoxhere** [comment]
Where did you get such info? This is not correct

> according to the new version of Kolka, earning rewards will significantly drop after 25 workers

**Comment by naphob** [comment]
> Where did you get such info? This is not correct
> 
> > according to the new version of Kolka, earning rewards will significantly drop after 25 workers

ok. I might be wrong. it's what I read from your chat in discord

**Comment by uhakito** [comment]
> ### hello i mine with 50 arduino but the mining share is very low
> ![Capture381dcb27cff17fea.png](https://camo.githubusercontent.com/855e0c27dc50484290832e7fc222c66e6a91042598320944333b21fd046be12e/68747470733a2f2f69302e77702e636f6d2f73312e757068696e682e6f72672f323032312f30382f31332f43617074757265333831646362323763666631376665612e706e67)

![_20210814_090339](https://user-images.githubusercontent.com/88104972/129436137-75e390a7-6c0b-43d9-afae-86e2552ece4d.JPG)
