### ISSUE TITLE
I heard the reward is limited after 25 devices

### ISSUE THREAD

**Issue by logdaubui** [revoxhere/duino-coin#805]
I don't think it's fair that people invest so much in equipment

**Comment by primitt** [comment]
Whats your issue here..... we limit it so that people dont buy 10000 arduinos and 
1. Kill the network
2. Use the same power as 1 bitcoin ASIC

**Comment by logdaubui** [comment]
i try to mine some arduino and their rewards are the same

**Comment by Elheims** [comment]
They need to read the whitepaper 😅

**Comment by revoxhere** [comment]
This is not true, if it was, it'd be clearly announced somewhere
