### ISSUE TITLE
error when mining with cpu

### ISSUE THREAD

**Issue by thienduongtungtang** [revoxhere/duino-coin#815]
### when i mine with pc cpu but duco is not added to my account ###

**Comment by thienduongtungtang** [comment]
> Nếu bạn đang khai thác trên PulsePool, vui lòng đợi vài giờ vì gần đây máy chủ chính đang gặp sự cố (thời gian chết) và số dư của bạn sẽ được cập nhật khi máy chủ chính trực tuyến trở lại! Xin vui lòng cho tôi biết nếu nó đã được cập nhật vào lúc đó, cảm ơn!

ok thansk !!!

**Comment by thienduongtungtang** [comment]
> Nếu bạn đang khai thác trên PulsePool, vui lòng chờ vài giờ vì gần đây chính máy chủ đang gặp sự cố (thời gian chết) và số dư của bạn sẽ được cập nhật khi máy chủ trực tuyến trở lại! Xin vui lòng cho tôi biết nếu nó đã được cập nhật vào lúc đó, cảm ơn!

Thank you very much to the developer for fixing the bug

**Comment by Tech1k** [comment]
Glad I could help!
