### ISSUE TITLE
Esp8266 ota enable on 149.91.88.18:6000

### ISSUE THREAD

**Issue by mrgh14** [revoxhere/duino-coin#846]
### **

> Hi please if possible port 6000 for server 149.91.88.18 Temporarily activate until we have time to update esp8266 boards. Unfortunately, updating the OTA is only possible when the server is active.

**

**Comment by BastelPichi** [comment]
Can you give more information?

**Comment by mrgh14** [comment]
hi when pool server with ip adrress 149.91.88.18 on port 6000 is active my esp8266 miner  working truely and OTA flashing is active too
now server with 149.91.88.18 on port 6000 adrress is not working and OTA Flashing is not working
ESP8266_code.ino

namespace {
  const char* ssid          = "WiFi SSID";   // Change this to your WiFi SSID
  const char* password      = "WiFi Pass";    // Change this to your WiFi password
  const char* ducouser      = "DUCO Username";     // Change this to your Duino-Coin username
  const char* rigIdentifier = "None";       // Change this if you want a custom miner name
  
  const char * host = 149.91.88.18"; // Static server IP
  const int port = 6000;
  unsigned int Shares = 0; // Share variable

**Comment by BastelPichi** [comment]
This version of code is outdated. Please update it manually. For the moment mining is disabled, so it wont work either.

**Comment by Tech1k** [comment]
Mining has since been reenabled and this issue should be resolved by upgrading your miner to the latest version!
