### ISSUE TITLE
Globalise Shares and HashRate variables.

### ISSUE THREAD

**Issue by nigeljohnson73** [revoxhere/duino-coin#888]
**Is your feature request related to a problem? Please describe.**
No problem. ESP and ESP32 devices are not 'visible' while running in that you cannot see if they are submitting jobs, etc. I have written a function that will report in with a custom IOT service I have, so I can watch the share count go up.

In the ESP32 code, the `share_count` variable is never updated. Each task has a local `Shares`/`Shares1` variable that is updated. There are also Task-based hash rates that would be nice to all see globally.

**Describe the solution you'd like**
Move the `Shares` and `Shares1` variable definitions globally (same with `HashRate` variables)

**Describe alternatives you've considered**
I am not sure how threadsafe this will be. In the context of the core code, there should be no problem because each Task will write to its own global variable, and nothing else will interfere with that.

**Additional context**
I'm happy to create the pull request if you're ok with this as it's just moving variable declarations to a local scope. I'll also add a skeleton task.

**Comment by revoxhere** [comment]
You can create a PR if you want, the idea sounds good
