### ISSUE TITLE
Arduino Hashing Speed

### ISSUE THREAD

**Issue by uhakito** [revoxhere/duino-coin#902]
why the hashing speed on avr miner is higher than dashboard?
hashing speed on avr miner is stable at 195 h/s but varies on dashboard. the highest is only 75 h/s.

**Comment by Izder456** [comment]
may I ask why you are mining on AVR when AVR mining has been disabled?

**Comment by uhakito** [comment]
> may I ask why you are mining on AVR when AVR mining has been disabled?

The screenshot above I took yesterday when I was mining before avr mining was disabled
