### ISSUE TITLE
Error connecting to AVR! Retrying in 10s. how do I enable AVR miner.

### ISSUE THREAD

**Issue by TusharChillal** [revoxhere/duino-coin#903]
I tries 3 different typed of Arduino boards and the sam same issue cam up please help me 

![Screenshot 2021-08-27 at 4 26 50 PM](https://user-images.githubusercontent.com/80667954/131117459-33fc3802-22d9-4fe1-9b29-8642b8bcaa60.png)

**System (please complete the following information):**
 - OS: [MAC]
 - Software [ AVR_Miner]
 - Version [2.6.1]

**Comment by revoxhere** [comment]
![image](https://user-images.githubusercontent.com/50244265/131119300-554eb02b-a04f-4965-a473-4fc6646e5f68.png)

**Comment by TusharChillal** [comment]
how can I enable it
