### ISSUE TITLE
How do I enable AVR miner on Mac pls help me 

### ISSUE THREAD

**Issue by TusharChillal** [revoxhere/duino-coin#904]
![Screenshot 2021-08-27 at 4 26 50 PM](https://user-images.githubusercontent.com/80667954/131121073-d863b184-cb64-489e-8f95-d422c23fd9aa.png)

 - OS: [MAC]
 - Software [AVR_Miner]
 - Version [2.6.1]

thank you for you help

**Comment by revoxhere** [comment]
Avr mining is disabled
