### ISSUE TITLE
CLI_Wallet.py version 2.7.1

### ISSUE THREAD

**Issue by uhakito** [revoxhere/duino-coin#961]
'str' object has no attribute 'decode'
![_20210905_164906](https://user-images.githubusercontent.com/88104972/132122599-295fea1f-0941-4ad9-96b0-95a5a9294584.JPG)

**Comment by rhjdjcbcz** [comment]
The same situation

**Comment by revoxhere** [comment]
Hello, please use the Web wallet for now.

**Comment by uhakito** [comment]
> Hello, please use the Web wallet for now.

okay thank you

**Comment by BastelPichi** [comment]
Closed due to inactivity, feel free to reopen if needed.
